
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ENTRY_SEP INDEX NEWLINE OPEN_CAT OPEN_FULL OPEN_LANG OPEN_NOTE OPEN_REM OPEN_SIN OPEN_VAR OPEN_VID SEPARATOR TEXTentries : entry ENTRY_SEP entries\n               | entryentry : OPEN_FULL full_entryentry : OPEN_REM rem_entryfull_entry : INDEX SEPARATOR TEXT SEPARATOR TEXT NEWLINE full_elementsfull_elements : full_element remaining_elementsremaining_elements : NEWLINE full_element remaining_elementsremaining_elements : full_element : OPEN_CAT text_listfull_element : OPEN_SIN text_listfull_element : OPEN_VAR text_listfull_element : '[' OPEN_LANG ']' ':' translation_listfull_element : OPEN_NOTE TEXTtext_list : TEXT SEPARATOR text_listtext_list : TEXTtranslation_list : TEXT '[' OPEN_LANG ']' remaining_translations\n                        | TEXT remaining_translationsremaining_translations : SEPARATOR TEXT '[' OPEN_LANG ']' remaining_translations\n                              | SEPARATOR TEXT remaining_translationsremaining_translations : rem_entry : TEXT NEWLINE OPEN_VID text_list"
    
_lr_action_items = {'OPEN_FULL':([0,5,],[3,3,]),'OPEN_REM':([0,5,],[4,4,]),'$end':([1,2,6,8,10,16,17,21,22,23,29,31,32,33,35,36,38,40,41,43,46,47,49,50,52,53,],[0,-2,-3,-4,-1,-15,-21,-14,-5,-8,-6,-9,-10,-11,-13,-8,-7,-12,-20,-17,-20,-20,-19,-16,-20,-18,]),'ENTRY_SEP':([2,6,8,16,17,21,22,23,29,31,32,33,35,36,38,40,41,43,46,47,49,50,52,53,],[5,-3,-4,-15,-21,-14,-5,-8,-6,-9,-10,-11,-13,-8,-7,-12,-20,-17,-20,-20,-19,-16,-20,-18,]),'INDEX':([3,],[7,]),'TEXT':([4,11,14,15,19,24,25,26,28,39,44,],[9,13,16,18,16,16,16,16,35,41,46,]),'SEPARATOR':([7,13,16,41,46,47,52,],[11,15,19,44,44,44,44,]),'NEWLINE':([9,16,18,21,23,31,32,33,35,36,40,41,43,46,47,49,50,52,53,],[12,-15,20,-14,30,-9,-10,-11,-13,30,-12,-20,-17,-20,-20,-19,-16,-20,-18,]),'OPEN_VID':([12,],[14,]),'OPEN_CAT':([20,30,],[24,24,]),'OPEN_SIN':([20,30,],[25,25,]),'OPEN_VAR':([20,30,],[26,26,]),'[':([20,30,41,46,],[27,27,42,48,]),'OPEN_NOTE':([20,30,],[28,28,]),'OPEN_LANG':([27,42,48,],[34,45,51,]),']':([34,45,51,],[37,47,52,]),':':([37,],[39,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'entries':([0,5,],[1,10,]),'entry':([0,5,],[2,2,]),'full_entry':([3,],[6,]),'rem_entry':([4,],[8,]),'text_list':([14,19,24,25,26,],[17,21,31,32,33,]),'full_elements':([20,],[22,]),'full_element':([20,30,],[23,36,]),'remaining_elements':([23,36,],[29,38,]),'translation_list':([39,],[40,]),'remaining_translations':([41,46,47,52,],[43,49,50,53,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> entries","S'",1,None,None,None),
  ('entries -> entry ENTRY_SEP entries','entries',3,'p_entries','my_parser.py',96),
  ('entries -> entry','entries',1,'p_entries','my_parser.py',97),
  ('entry -> OPEN_FULL full_entry','entry',2,'p_entry_1','my_parser.py',100),
  ('entry -> OPEN_REM rem_entry','entry',2,'p_entry_2','my_parser.py',104),
  ('full_entry -> INDEX SEPARATOR TEXT SEPARATOR TEXT NEWLINE full_elements','full_entry',7,'p_full_entry','my_parser.py',108),
  ('full_elements -> full_element remaining_elements','full_elements',2,'p_full_elements','my_parser.py',126),
  ('remaining_elements -> NEWLINE full_element remaining_elements','remaining_elements',3,'p_remaining_elements_1','my_parser.py',131),
  ('remaining_elements -> <empty>','remaining_elements',0,'p_remaining_elements_2','my_parser.py',136),
  ('full_element -> OPEN_CAT text_list','full_element',2,'p_full_element_1','my_parser.py',140),
  ('full_element -> OPEN_SIN text_list','full_element',2,'p_full_element_2','my_parser.py',144),
  ('full_element -> OPEN_VAR text_list','full_element',2,'p_full_element_3','my_parser.py',148),
  ('full_element -> [ OPEN_LANG ] : translation_list','full_element',5,'p_full_element_4','my_parser.py',152),
  ('full_element -> OPEN_NOTE TEXT','full_element',2,'p_full_element_5','my_parser.py',157),
  ('text_list -> TEXT SEPARATOR text_list','text_list',3,'p_text_list_1','my_parser.py',162),
  ('text_list -> TEXT','text_list',1,'p_text_list_2','my_parser.py',167),
  ('translation_list -> TEXT [ OPEN_LANG ] remaining_translations','translation_list',5,'p_translation_list','my_parser.py',171),
  ('translation_list -> TEXT remaining_translations','translation_list',2,'p_translation_list','my_parser.py',172),
  ('remaining_translations -> SEPARATOR TEXT [ OPEN_LANG ] remaining_translations','remaining_translations',6,'p_remaining_translations_1','my_parser.py',181),
  ('remaining_translations -> SEPARATOR TEXT remaining_translations','remaining_translations',3,'p_remaining_translations_1','my_parser.py',182),
  ('remaining_translations -> <empty>','remaining_translations',0,'p_remaining_translations_2','my_parser.py',191),
  ('rem_entry -> TEXT NEWLINE OPEN_VID text_list','rem_entry',4,'p_rem_entry','my_parser.py',195),
]
